### ISSUE TITLE
Bug: Incrementing the time from snooze does not portray the time left in a user friendly way

### ISSUE THREAD

**Issue by Wreck-X** [CCExtractor/ultimate_alarm_clock#508]
### Description

When incremented enough, The timer is always of the format MM:SS, I believe its better to change the format of the time when it hits the 60 minutes mark to either HH:MM:SS or switch to HH:MM.

additionally i also think it would be better to move the incrementing buttons towards the bottom that is above the snooze button making it easier for the users to tap on them.

I would like to be assigned to this issue 

### Screenshots

![image](https://github.com/CCExtractor/ultimate_alarm_clock/assets/72601105/4928be85-c45f-433a-8d96-143309045fe1)

**Comment by Wreck-X** [comment]
if its approved please assign this to me as id like to work on this :)

**Comment by mohnishdeshpande** [comment]
Hi @Wreck-X, I was the one adding snooze buttons, I specifically positioned them close to the timer display. If it were closer to the 'dismiss' button, in a user workflow it is possible to hit the 'dismiss' button instead of the add snooze timers, and failing the whole point of the alarm clock app.
And for the display of hours in timer, I wonder if that's necessary because then we would have the '00' sitting there (if implemented according to the current design) idle most of the time, as a user would rarely go past 30 mins of snoozing, let alone an hour.
However, if the maintainers think that the changes should be made, either of us can work on it.

**Comment by Wreck-X** [comment]
The timer need not necessarily display the 00: all the time it could add the field incase it goes over the 60 minutes, as for the position of the buttons I guess it's fine to keep it at the top if the idea was to avoid misclicks.

**Comment by MarkisDev** [comment]
Although I doubt anyone is going to be snoozing for over 60 minutes, I think its good to handle the case anyway. I'll assign this to you, ler's show the HH only when it is necessary. As for the buttons - I agree with @mohnishdeshpande too close to dismiss would be a bad idea.

**Comment by ganidande905** [comment]
Hi @Wreck-X are you still working on this issue
If not, could you assign this issue to me @MarkisDev

**Comment by Wreck-X** [comment]
im not working on this anymore feel free to work on it

**Comment by AryanSarafDev** [comment]
> Hi @Wreck-X are you still working on this issue If not, could you assign this issue to me @MarkisDev @AryanSarafDev

@ganidande905  I think this issue is not required anymore because the ui and flow has shifted to a different implementation. But you can think of implementing a snooze button for the new timer ui for individual timers and create a new issue for it. I am closing this issue. You can also try implementing quick timer options for like 1 min 5 min etc!
